language: c

# Setup Build Matrix
compiler: 
 - clang
 - gcc

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created using:
    # travis encrypt COVERITY_SCAN_TOKEN="xxxxxxx-xxxxxxx" -r dkgroot/chan-sccp-b
    - secure: "QKOkim25QeUSBfbqKvR8Gh3Lt5+yuZqd1m3yXVuQnvxK9CmUPEh6009v3pzdFzQIAid5H8PHioS6MeKLsrJikPccvs/utiKMkQhxTH9OiddhG1SExEu6wE77Vpa+3+iWZS1Xyer4FK2KpY9mAOH3DgGCWji/5LPu/11MCR5MABZ0+TmxXbR75KkEhxg7s7OtiF1wGIrroLR9WiAbpb2+iZ7yaoReaV5+mjRKnUJv8ztugiiU6Jq9m0fIdfPqYYsdVuS7/OGOSHM0LzBoeOPG0ZX1QGXlCxXzvVE7AA6gWgSdRwmHtYkw6lzsZQrIpyNrksHwky0HfWoHP9hhEp6vC3aEKn20/pTc7HunglyzSS6DTaXCuoq4v6ZFAAzqNyf+sDF9Z2yjIk5XOIPmpzPeyxPSJXA+LPwnH5Dhpf0qmShJ2HYPhB0DzhDLKdWRhH9N1SMj7q03lh74r+CI+Oyyo7laJJz+whzTstp+hOuUTxQYBvg412gpATvwOXbxFw1f65qm5evC27GA3FYBfnxmyApoveERcvG+2oj7N276RCyGLXmhnOeH2aF7qfQOLAKeMcl32hHPsS2eNoCv5lYzxtbP5lUKmX/FKqrtpvQKy6jW8GLLEZXmx7cM0hLGt5pG3J6IRHPX9zJdyshJWyxI2tl0fPE34Y3uhCyWfPfpJZk="
  matrix:
    - REPOS=precise
    - REPOS=trusty
    - REPOS=trusty13
    - REPOS=utopic

# Install Required Devel Packages
before_install:
 - if [ "${REPOS}" != "trusty13" ]; 
   then
     echo "deb http://archive.ubuntu.com/ubuntu ${REPOS} main restricted universe multiverse"            | sudo tee -a /etc/apt/sources.list.d/trusty.list;
     echo "deb http://archive.ubuntu.com/ubuntu ${REPOS}-updates main restricted universe multiverse"    | sudo tee -a /etc/apt/sources.list.d/trusty.list;
     echo "deb http://security.ubuntu.com/ubuntu/ ${REPOS}-security main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/trusty.list;
     echo "deb http://archive.canonical.com/ubuntu/ ${REPOS} partner"                                    | sudo tee -a /etc/apt/sources.list.d/trusty.list;
     sudo apt-get update -qq;
     sudo apt-get install -qq libblocksruntime0 libblocksruntime-dev asterisk asterisk-dev asterisk-config asterisk-modules binutils.dev libc6-dev;
   else
     echo "deb http://archive.ubuntu.com/ubuntu trusty main restricted universe multiverse"              | sudo tee -a /etc/apt/sources.list.d/trusty.list;
     echo "deb http://archive.ubuntu.com/ubuntu trusty-updates main restricted universe multiverse"      | sudo tee -a /etc/apt/sources.list.d/trusty.list;
     echo "deb http://security.ubuntu.com/ubuntu/ trusty-security main restricted universe multiverse"   | sudo tee -a /etc/apt/sources.list.d/trusty.list;
     echo "deb http://archive.canonical.com/ubuntu/ trusty partner"                                      | sudo tee -a /etc/apt/sources.list.d/trusty.list;
     sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 9C245DE2;
     echo "deb http://ppa.launchpad.net/jan-hoffmann/asterisk13/ubuntu trusty main"                      | sudo tee -a /etc/apt/sources.list.d/asterisk13.list;
     echo "deb-src http://ppa.launchpad.net/jan-hoffmann/asterisk13/ubuntu trusty main"			 | sudo tee -a /etc/apt/sources.list.d/asterisk13.list;
     sudo apt-get update -qq;
     sudo apt-get install -qq libblocksruntime0 libblocksruntime-dev libpj2 libpjmedia2 libpjnath2 libpjproject-dev libpjsip2 libpjsua2 libpjsua2-2 asterisk asterisk-dev asterisk-config asterisk-modules asterisk-dbg binutils.dev libc6-dev;
   fi

# Prepare Configure Script
before_script:
 - autoreconf -fi

# Report Results
notifications:
  slack: chan-sccp:yfQzKYTnTf4cD1iHElnTYsXD
  email:
    recipients:
      - ddegroot@talon.nl
      - marcelloceschia@users.sourceforge.net

addons:
  coverity_scan:
    project:
      name: "dkgroot/chan-sccp-b"
      description: "Asterisk SCCP Channel Addon"
    notification_email: info@talon.nl
    build_command_prepend: "./configure --enable-video --enable-conference --enable-distributed-devicestate --enable-advanced-functions && make clean"
    build_command: "make -j2"
    branch_pattern: master

matrix:
  exclude:
    - compiler: clang
    - env: REPOS=precise COVERITY_SCAN_BRANCH=1
    - env: REPOS=trusty COVERITY_SCAN_BRANCH=1
    - env: REPOS=trusty13 COVERITY_SCAN_BRANCH=1
    - env: REPOS=utopic COVERITY_SCAN_BRANCH=1
  exclude:
    - compiler: gcc
    - env: REPOS=precise COVERITY_SCAN_BRANCH=1
    - env: REPOS=trusty COVERITY_SCAN_BRANCH=1
    - env: REPOS=utopic COVERITY_SCAN_BRANCH=1
  allow_failures:
    - env: REPOS=trusty13 COVERITY_SCAN_BRANCH=1

